name: "sample go action"
description: "sample go action"
inputs:
    src:
        description: "source directory"
        required: true
        default: ""
    dist:
        description: "destination directory"
        required: true
        default: ""
runs:
    using: "composite"
    steps:
        - run: go run ${{ github.action_path }}/main.go ${{ inputs.src }} ${{ inputs.dist }}
          shell: bash
